services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8090:80"
    user: "1000:1000"
    environment:
      - FB_BASEURL=/filebrowser
    volumes:
      - /opt/tomcat:/srv/opt
      - filebrowser_database:/database
      - /srv/docker-data/filebrowser/settings/:/config

volumes:
  filebrowser_database:
  #filebrowser_config:
